// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr56Wh4stNaHoDWGsrq1NAtFgUrR45Hw0',
    appId: '1:302704940049:web:2821d55cf68d18d856cdb0',
    messagingSenderId: '302704940049',
    projectId: 'reapp-d4d07',
    authDomain: 'reapp-d4d07.firebaseapp.com',
    storageBucket: 'reapp-d4d07.appspot.com',
    measurementId: 'G-0LM8M63RYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB54gO88D9aAXPtmO5capfnm_93bvkWmo',
    appId: '1:302704940049:android:161ed357f50465d356cdb0',
    messagingSenderId: '302704940049',
    projectId: 'reapp-d4d07',
    storageBucket: 'reapp-d4d07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQV9ONdu7-Tm0azlmkdFMZ_SAGgNriBLI',
    appId: '1:302704940049:ios:7b62511acd1287b156cdb0',
    messagingSenderId: '302704940049',
    projectId: 'reapp-d4d07',
    storageBucket: 'reapp-d4d07.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQV9ONdu7-Tm0azlmkdFMZ_SAGgNriBLI',
    appId: '1:302704940049:ios:6d3039219031aacf56cdb0',
    messagingSenderId: '302704940049',
    projectId: 'reapp-d4d07',
    storageBucket: 'reapp-d4d07.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
